sonar.projectKey=maximkozhin24_transproject
sonar.organization=maximkozhin24

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml